sudo: required

language: generic

cache:
  directories:
    - /home/travis/docker

services:
  - docker

jobs:
  include:
    - stage: image
      script: |
        # See if this is needed
        git diff-index --name-only "HEAD^" | grep -e docker/ci_dockerfile -e Cargo.lock -e rust-toolchain -e .travis.yml || [ ! -f  /home/travis/docker/ci.tar.gz ] || exit 0
        apt-get install pv --yes
        # Do a build
        docker build -t ci --force-rm --no-cache -f docker/ci_dockerfile .
        df -h
        docker images
        mkdir -p /home/travis/docker
        docker save ci | pv -cN image > /home/travis/docker/ci.tar.gz
    - stage: lint
      script: |
        zcat /home/travis/docker/ci.tar.gz | docker load
        docker run -ti --rm -v `pwd`:/build ci bash -c <<-EOF
          cd /build &&
          ln /cache/target target &&
          (cargo fmt --all -- --check) &&
          (cargo clippy --all -- -D clippy)
        EOF
    - stage: test
      script: |
        docker run -ti --rm ci bash -c <<-EOF
          cd /build &&
          ln /cache/target target &&
          cargo test --all --benches &&
        EOF
